name: CI
on: [pull_request]
jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
        with:
          node-version: "16"

      - name: Run npm install
        run: npm ci

      - name: Lint Filenames Glob
        uses: scheduleonce/lint-filenames@v2.0.0
        with:
          path: "./pi-*/**"
          pattern: "^[a-z0-9.-]+$"

      - name: Run Prettier check
        run: npm run prettier
